image: node:9.11.1

cache:
  paths:
    - node_modules/

services:
  - mongo:3.4.0

variables:
  MONGO_URL: http://mongo:27017/arachne

stages:
  - test
  - deploy

check_lint:
  stage: test
  script:
    - node -v
    - eslint .

arachne:
  stage: deploy
  script:
    - node -v
    - npm install
    - node brain.js