image: node:alpine

cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true
  paths:
    - node_modules/

variables:
  NODE_ENV: "production"
  NPM_CONFIG_LEVEL: "warn"

stages:
  - lint
  - build
  - test
  - security
  - staging

check_lint:
  tags:
    - node
  stage: lint
  script:
    - npm install -g eslint
    - eslint .

building:
  tags:
    - node
  stage: build
  before_script:
    - apk add --no-cache --virtual git
    - apk --no-cache add --virtual builds-deps build-base python # required for alpine based images to build bcrypt. (see https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images)
  script:
    - npm install
    - npm rebuild bcrypt --build-from-source # rebuild bcrypt for alpine based images. (see https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images)
  allow_failure: false

package-scan:
  tags:
    - node
  stage: test
  before_script:
    - npm install -g npm-check
  script:
    - npm-check --skip-unused --production
  allow_failure: true

snyk-security-scan:
  tags:
    - node
  stage: security
  before_script:
    - npm install -g snyk && snyk auth $SNYK_TOKEN
  script:
    - snyk test
  allow_failure: true

nsp-security-scan:
  tags:
    - node
  stage: security
  before_script:
    - npm install -g nsp
  script:
    - nsp test
  allow_failure: true

retire-security-scan:
  tags:
    - node
  stage: security
  before_script:
    - npm install -g retire
  script:
    - retire
  allow_failure: true

deploy_staging:
  tags:
    - node
  stage: staging
  before_script:
    - apk add --no-cache --virtual git
    - apk add --no-cache --virtual openssh
    - echo "$DOKKU_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "dokku.${DOKKU_DOMAIN}" >> ~/.ssh/known_hosts
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_ID"
  script:
    - echo "Pushing to Dokku..."
    - git push --force ssh://dokku@dokku.${DOKKU_DOMAIN}/${DOKKU_APP} HEAD:refs/heads/master
    - echo "Pushed to Dokku."
  environment:
    name: staging
    url: https://${DOKKU_APP}.${DOKKU_DOMAIN}
  only:
    - tags