image: node:9.11.1

cache:
  paths:
    - node_modules/

services:
  - mongo:3.4.0

variables:
  MONGO_URL: mongodb://mongo:27017/arachne

stages:
  - test

check_lint:
  stage: test
  script:
    - npm install -g eslint
    - eslint .